### ISSUE TITLE
[JOSS] Improving the documentation

### ISSUE THREAD

**Issue by aymgal** [EdwardBerman/shopt#9]
This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6144) process.

I have been following the installation instructions and running of the program on the test catalog. Here are some comments regarding the documentation.

- The part on how to compile Python libraries for use in Julia is not straightforward to follow. In particular, it is not clear that there are three, even four, ways to achieve the same thing. I advise to re-formulate this part, stating ahead that there are these X different ways (e.g., as a list), and guide the user to the right section, instead of having all the commands in a row.
- It is important that the command `pyimport("astropy")` should be run _after_ re-loading the Julia REPL, so it would better to have this explicitely mentioned.
- Is the `TutorialNotebook.ipynb` made just for copy-pasting lines of codes into the Julia REPL, or can this be executed using Julia directly? This is not clear to me. Probably because this is the first time I run Julia code: it means that the documentation can be be improved.
- `using Base.Threads` is missing in `TutorialNotebook.ipynb`.

**Comment by EdwardBerman** [comment]
I am continuing to work on the first two bullets. For the latter two: 
 
- The TutorialNotebook is made to give the user a sense of order in which things should be done. Things can be executed within the notebook or copy and pasted into Julia desired. I clarify this with this commit: [96e97be](https://github.com/EdwardBerman/shopt/commit/96e97be360d257f4fe410d53508424dcf9b75d98)
- "using Base.Threads is missing in TutorialNotebook.ipynb." This is now fixed with commits [bb278d6](https://github.com/EdwardBerman/shopt/commit/bb278d6c3709323724689bdcf226434fa9256570)  [85e67c18a4cf420c9c721a24b985613516bde6a7](https://github.com/EdwardBerman/shopt/commit/85e67c18a4cf420c9c721a24b985613516bde6a7)

**Comment by EdwardBerman** [comment]
The first two bullets have been addressed in commits [ba6d571](https://github.com/EdwardBerman/shopt/commit/ba6d571be5521b3e2ccbb43578e3b3c58e422264) through [6b4e764](https://github.com/EdwardBerman/shopt/commit/6b4e764bdc93e82f01b6bee88db401099556835f)!

**Comment by aymgal** [comment]
Great, I'm happy with these changes, I close this issue :)
